### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by tsrobcvai** [higgsas/higgsas_geo_nodes_manual#1]
There is a bug for Bend node in the Higgsas Geo Nodes Blender 3.6 Assets:
1.  When it rotates along the Y axis, it works wrong.
![image](https://github.com/higgsas/higgsas_geo_nodes_manual/assets/73679440/1d4e0825-1d1f-422e-8d45-65e505dc3a02)

2. When it rotates along the Z axis, it works very well
![image](https://github.com/higgsas/higgsas_geo_nodes_manual/assets/73679440/a48e7193-9a13-4385-b532-4b670c9a513c)

**Comment by higgsas** [comment]
Hello,

Unfortunately it is a limitation not a bug. You need to set Axis Rotation to X 90 degrees (similar how it's done in Simple Deform using empty )

![image](https://github.com/higgsas/higgsas_geo_nodes_manual/assets/59316820/53fb7624-9573-49e0-aad1-a877163f6367)

Currently I don't have a automatic solution without manually setting axis rotation.
